// <auto-generated />
using System;
using FreightManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreightManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreightManagement.Models.DonHang", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<int>("ChiPhi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(SoLuong * DonGia) PERSISTED");

                    b.Property<string>("DiaChiGui")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChiNhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaQLK")
                        .HasColumnType("int");

                    b.Property<int?>("MaTX")
                        .HasColumnType("int");

                    b.Property<string>("MoTaHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SdtNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDon");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaQLK");

                    b.HasIndex("MaTX");

                    b.ToTable("DonHang", null, t =>
                        {
                            t.HasTrigger("trg_HangXuatKho");

                            t.HasTrigger("trg_LichSuTrangThai");

                            t.HasTrigger("trg_ThongKeDoanhThu");

                            t.HasTrigger("trg_TinhChiPhi");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FreightManagement.Models.HangTrongKho", b =>
                {
                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianVaoKho")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXuatKho")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKho", "MaDon");

                    b.HasIndex("MaDon")
                        .IsUnique();

                    b.ToTable("HangTrongKho", null, t =>
                        {
                            t.HasTrigger("trg_HangVaoKho");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FreightManagement.Models.KhoHang", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<string>("DiaChiKho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaQLK")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKho");

                    b.HasIndex("MaQLK");

                    b.ToTable("KhoHang", (string)null);

                    b.HasData(
                        new
                        {
                            MaKho = 1,
                            DiaChiKho = "Hà Nội",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 500,
                            TenKho = "Kho Hà Nội"
                        },
                        new
                        {
                            MaKho = 2,
                            DiaChiKho = "TP.HCM",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 800,
                            TenKho = "Kho TP.HCM"
                        },
                        new
                        {
                            MaKho = 3,
                            DiaChiKho = "Hải Phòng",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 400,
                            TenKho = "Kho Hải Phòng"
                        },
                        new
                        {
                            MaKho = 4,
                            DiaChiKho = "Đà Nẵng",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Đà Nẵng"
                        },
                        new
                        {
                            MaKho = 5,
                            DiaChiKho = "Cần Thơ",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 350,
                            TenKho = "Kho Cần Thơ"
                        },
                        new
                        {
                            MaKho = 6,
                            DiaChiKho = "An Giang",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho An Giang"
                        },
                        new
                        {
                            MaKho = 7,
                            DiaChiKho = "Bà Rịa - Vũng Tàu",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho BR - VT"
                        },
                        new
                        {
                            MaKho = 8,
                            DiaChiKho = "Bắc Giang",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Bắc Giang"
                        },
                        new
                        {
                            MaKho = 9,
                            DiaChiKho = "Bắc Kạn",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 200,
                            TenKho = "Kho Bắc Kạn"
                        },
                        new
                        {
                            MaKho = 10,
                            DiaChiKho = "Bạc Liêu",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Bạc Liêu"
                        },
                        new
                        {
                            MaKho = 11,
                            DiaChiKho = "Bắc Ninh",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Bắc Ninh"
                        },
                        new
                        {
                            MaKho = 12,
                            DiaChiKho = "Bến Tre",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Bến Tre"
                        },
                        new
                        {
                            MaKho = 13,
                            DiaChiKho = "Bình Định",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Bình Định"
                        },
                        new
                        {
                            MaKho = 14,
                            DiaChiKho = "Bình Dương",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 500,
                            TenKho = "Kho Bình Dương"
                        },
                        new
                        {
                            MaKho = 15,
                            DiaChiKho = "Bình Phước",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Bình Phước"
                        },
                        new
                        {
                            MaKho = 16,
                            DiaChiKho = "Bình Thuận",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Bình Thuận"
                        },
                        new
                        {
                            MaKho = 17,
                            DiaChiKho = "Cà Mau",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Cà Mau"
                        },
                        new
                        {
                            MaKho = 18,
                            DiaChiKho = "Cao Bằng",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 200,
                            TenKho = "Kho Cao Bằng"
                        },
                        new
                        {
                            MaKho = 19,
                            DiaChiKho = "Đắk Lắk",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Đắk Lắk"
                        },
                        new
                        {
                            MaKho = 20,
                            DiaChiKho = "Đắk Nông",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Đắk Nông"
                        },
                        new
                        {
                            MaKho = 21,
                            DiaChiKho = "Điện Biên",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 200,
                            TenKho = "Kho Điện Biên"
                        },
                        new
                        {
                            MaKho = 22,
                            DiaChiKho = "Đồng Nai",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 500,
                            TenKho = "Kho Đồng Nai"
                        },
                        new
                        {
                            MaKho = 23,
                            DiaChiKho = "Đồng Tháp",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Đồng Tháp"
                        },
                        new
                        {
                            MaKho = 24,
                            DiaChiKho = "Gia Lai",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Gia Lai"
                        },
                        new
                        {
                            MaKho = 25,
                            DiaChiKho = "Hà Giang",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 200,
                            TenKho = "Kho Hà Giang"
                        },
                        new
                        {
                            MaKho = 26,
                            DiaChiKho = "Hà Nam",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Hà Nam"
                        },
                        new
                        {
                            MaKho = 27,
                            DiaChiKho = "Hà Tĩnh",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Hà Tĩnh"
                        },
                        new
                        {
                            MaKho = 28,
                            DiaChiKho = "Hải Dương",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Hải Dương"
                        },
                        new
                        {
                            MaKho = 29,
                            DiaChiKho = "Hậu Giang",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Hậu Giang"
                        },
                        new
                        {
                            MaKho = 30,
                            DiaChiKho = "Hòa Bình",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Hòa Bình"
                        },
                        new
                        {
                            MaKho = 31,
                            DiaChiKho = "Hưng Yên",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Hưng Yên"
                        },
                        new
                        {
                            MaKho = 32,
                            DiaChiKho = "Khánh Hòa",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Khánh Hòa"
                        },
                        new
                        {
                            MaKho = 33,
                            DiaChiKho = "Kiên Giang",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Kiên Giang"
                        },
                        new
                        {
                            MaKho = 34,
                            DiaChiKho = "Kon Tum",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 200,
                            TenKho = "Kho Kon Tum"
                        },
                        new
                        {
                            MaKho = 35,
                            DiaChiKho = "Lai Châu",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 200,
                            TenKho = "Kho Lai Châu"
                        },
                        new
                        {
                            MaKho = 36,
                            DiaChiKho = "Lâm Đồng",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Lâm Đồng"
                        },
                        new
                        {
                            MaKho = 37,
                            DiaChiKho = "Lạng Sơn",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Lạng Sơn"
                        },
                        new
                        {
                            MaKho = 38,
                            DiaChiKho = "Lào Cai",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Lào Cai"
                        },
                        new
                        {
                            MaKho = 39,
                            DiaChiKho = "Long An",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 350,
                            TenKho = "Kho Long An"
                        },
                        new
                        {
                            MaKho = 40,
                            DiaChiKho = "Nam Định",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Nam Định"
                        },
                        new
                        {
                            MaKho = 41,
                            DiaChiKho = "Nghệ An",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 400,
                            TenKho = "Kho Nghệ An"
                        },
                        new
                        {
                            MaKho = 42,
                            DiaChiKho = "Ninh Bình",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Ninh Bình"
                        },
                        new
                        {
                            MaKho = 43,
                            DiaChiKho = "Ninh Thuận",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Ninh Thuận"
                        },
                        new
                        {
                            MaKho = 44,
                            DiaChiKho = "Phú Thọ",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Phú Thọ"
                        },
                        new
                        {
                            MaKho = 45,
                            DiaChiKho = "Phú Yên",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Phú Yên"
                        },
                        new
                        {
                            MaKho = 46,
                            DiaChiKho = "Quảng Bình",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Quảng Bình"
                        },
                        new
                        {
                            MaKho = 47,
                            DiaChiKho = "Quảng Nam",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Quảng Nam"
                        },
                        new
                        {
                            MaKho = 48,
                            DiaChiKho = "Quảng Ngãi",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Quảng Ngãi"
                        },
                        new
                        {
                            MaKho = 49,
                            DiaChiKho = "Quảng Ninh",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 400,
                            TenKho = "Kho Quảng Ninh"
                        },
                        new
                        {
                            MaKho = 50,
                            DiaChiKho = "Quảng Trị",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Quảng Trị"
                        },
                        new
                        {
                            MaKho = 51,
                            DiaChiKho = "Sóc Trăng",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Sóc Trăng"
                        },
                        new
                        {
                            MaKho = 52,
                            DiaChiKho = "Sơn La",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Sơn La"
                        },
                        new
                        {
                            MaKho = 53,
                            DiaChiKho = "Tây Ninh",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Tây Ninh"
                        },
                        new
                        {
                            MaKho = 54,
                            DiaChiKho = "Thái Bình",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Thái Bình"
                        },
                        new
                        {
                            MaKho = 55,
                            DiaChiKho = "Thái Nguyên",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Thái Nguyên"
                        },
                        new
                        {
                            MaKho = 56,
                            DiaChiKho = "Thanh Hóa",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 400,
                            TenKho = "Kho Thanh Hóa"
                        },
                        new
                        {
                            MaKho = 57,
                            DiaChiKho = "Thừa Thiên Huế",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Thừa Thiên Huế"
                        },
                        new
                        {
                            MaKho = 58,
                            DiaChiKho = "Tiền Giang",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Tiền Giang"
                        },
                        new
                        {
                            MaKho = 59,
                            DiaChiKho = "Trà Vinh",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Trà Vinh"
                        },
                        new
                        {
                            MaKho = 60,
                            DiaChiKho = "Tuyên Quang",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Tuyên Quang"
                        },
                        new
                        {
                            MaKho = 61,
                            DiaChiKho = "Vĩnh Long",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Vĩnh Long"
                        },
                        new
                        {
                            MaKho = 62,
                            DiaChiKho = "Vĩnh Phúc",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 300,
                            TenKho = "Kho Vĩnh Phúc"
                        },
                        new
                        {
                            MaKho = 63,
                            DiaChiKho = "Yên Bái",
                            MaQLK = 3,
                            SoLuongHienTai = 0,
                            SucChua = 250,
                            TenKho = "Kho Yên Bái"
                        });
                });

            modelBuilder.Entity("FreightManagement.Models.LichSuTrangThai", b =>
                {
                    b.Property<int>("MaLS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLS"));

                    b.Property<int?>("CapNhatBoi")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLS");

                    b.HasIndex("CapNhatBoi");

                    b.HasIndex("MaDon");

                    b.ToTable("LichSuTrangThai", (string)null);
                });

            modelBuilder.Entity("FreightManagement.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "KhachHang"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "QuanLyKho"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "TaiXe"
                        });
                });

            modelBuilder.Entity("FreightManagement.Models.ThongKeDoanhThu", b =>
                {
                    b.Property<int>("MaThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongKe"));

                    b.Property<int>("ChiPhiVanChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.HasKey("MaThongKe");

                    b.HasIndex("MaDon")
                        .IsUnique();

                    b.ToTable("ThongKeDoanhThu", (string)null);
                });

            modelBuilder.Entity("FreightManagement.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DiaChi = "Hà Nội",
                            Email = "admin@vanchuyen.com",
                            HoTen = "Admin Hệ Thống",
                            NgayTao = new DateTime(2026, 5, 12, 10, 25, 7, 681, DateTimeKind.Local).AddTicks(5318),
                            PasswordHash = "HASH_password123",
                            RoleId = 1,
                            SoDienThoai = "0900000001",
                            TrangThai = "HoatDong"
                        },
                        new
                        {
                            UserId = 2,
                            DiaChi = "TP.HCM",
                            Email = "khachhang@gmail.com",
                            HoTen = "Nguyễn Văn A",
                            NgayTao = new DateTime(2026, 5, 12, 10, 25, 7, 681, DateTimeKind.Local).AddTicks(5321),
                            PasswordHash = "HASH_password123",
                            RoleId = 2,
                            SoDienThoai = "0912345678",
                            TrangThai = "HoatDong"
                        },
                        new
                        {
                            UserId = 3,
                            DiaChi = "Đà Nẵng",
                            Email = "quanlykho@gmail.com",
                            HoTen = "Trần Thị B",
                            NgayTao = new DateTime(2026, 5, 12, 10, 25, 7, 681, DateTimeKind.Local).AddTicks(5323),
                            PasswordHash = "HASH_password123",
                            RoleId = 3,
                            SoDienThoai = "0987654321",
                            TrangThai = "HoatDong"
                        },
                        new
                        {
                            UserId = 4,
                            DiaChi = "Hà Nội",
                            Email = "taixe@gmail.com",
                            HoTen = "Lê Văn C",
                            NgayTao = new DateTime(2026, 5, 12, 10, 25, 7, 681, DateTimeKind.Local).AddTicks(5325),
                            PasswordHash = "HASH_password123",
                            RoleId = 4,
                            SoDienThoai = "0976543210",
                            TrangThai = "HoatDong"
                        },
                        new
                        {
                            UserId = 5,
                            DiaChi = "Hà Nội",
                            Email = "taixe1@gmail.com",
                            HoTen = "Lê Văn D",
                            NgayTao = new DateTime(2026, 5, 12, 10, 25, 7, 681, DateTimeKind.Local).AddTicks(5327),
                            PasswordHash = "HASH_password123",
                            RoleId = 4,
                            SoDienThoai = "0976543211",
                            TrangThai = "HoatDong"
                        });
                });

            modelBuilder.Entity("FreightManagement.Models.DonHang", b =>
                {
                    b.HasOne("FreightManagement.Models.Users", "KhachHang")
                        .WithMany("DonHangKhachHang")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightManagement.Models.Users", "QuanLyKho")
                        .WithMany("DonHangQuanLyKho")
                        .HasForeignKey("MaQLK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FreightManagement.Models.Users", "TaiXe")
                        .WithMany("DonHangTaiXe")
                        .HasForeignKey("MaTX")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("QuanLyKho");

                    b.Navigation("TaiXe");
                });

            modelBuilder.Entity("FreightManagement.Models.HangTrongKho", b =>
                {
                    b.HasOne("FreightManagement.Models.DonHang", "DonHang")
                        .WithOne("HangTrongKho")
                        .HasForeignKey("FreightManagement.Models.HangTrongKho", "MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FreightManagement.Models.KhoHang", "KhoHang")
                        .WithMany("HangTrongKhos")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhoHang");
                });

            modelBuilder.Entity("FreightManagement.Models.KhoHang", b =>
                {
                    b.HasOne("FreightManagement.Models.Users", "QuanLyKho")
                        .WithMany()
                        .HasForeignKey("MaQLK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("QuanLyKho");
                });

            modelBuilder.Entity("FreightManagement.Models.LichSuTrangThai", b =>
                {
                    b.HasOne("FreightManagement.Models.Users", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("CapNhatBoi")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FreightManagement.Models.DonHang", "DonHang")
                        .WithMany("LichSuTrangThais")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("NguoiCapNhat");
                });

            modelBuilder.Entity("FreightManagement.Models.ThongKeDoanhThu", b =>
                {
                    b.HasOne("FreightManagement.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("FreightManagement.Models.Users", b =>
                {
                    b.HasOne("FreightManagement.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FreightManagement.Models.DonHang", b =>
                {
                    b.Navigation("HangTrongKho");

                    b.Navigation("LichSuTrangThais");
                });

            modelBuilder.Entity("FreightManagement.Models.KhoHang", b =>
                {
                    b.Navigation("HangTrongKhos");
                });

            modelBuilder.Entity("FreightManagement.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FreightManagement.Models.Users", b =>
                {
                    b.Navigation("DonHangKhachHang");

                    b.Navigation("DonHangQuanLyKho");

                    b.Navigation("DonHangTaiXe");
                });
#pragma warning restore 612, 618
        }
    }
}
